/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import Entities.Log;
import Entities.VCar;
import Entities.Visit;
import Entities.Visitor;
import Facade.Logs;
import Facade.VCars;
import Facade.Visitors;
import Facade.Visits;
import Settings.DBSetting;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author anild
 */
public class ifrmNewVisit extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmNewVisit
     */
    public ifrmNewVisit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTRID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSurName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbisTRS = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtBirthDate = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCampanyName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbVisitD = new javax.swing.JComboBox<>();
        pnlCar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCarPlate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCarDetail = new javax.swing.JTextField();
        chkCar = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        cbSelectHabitant = new javax.swing.JComboBox<>();
        btnAddVisit = new javax.swing.JButton();

        setClosable(true);
        setTitle("Yeni Ziyareret Girişi");
        setToolTipText("");
        setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formİnternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ziyaretci Bilgileri"));

        jLabel1.setText("TC K No/Cep No:");

        jButton1.setText("Devam");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Adı:");

        txtName.setEnabled(false);

        jLabel3.setText("Soyadı:");

        txtSurName.setEnabled(false);

        jLabel4.setText("Uyruk:");

        cbisTRS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yabancı", "TC" }));
        cbisTRS.setEnabled(false);

        jLabel5.setText("Doğum Yılı:");

        txtBirthDate.setEnabled(false);

        jCheckBox1.setText("Kimlik Doğrulandı");
        jCheckBox1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName)
                    .addComponent(txtSurName)
                    .addComponent(cbisTRS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTRID, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBirthDate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTRID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSurName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbisTRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Araç/Firma Bilgileri"));

        jLabel6.setText("Firma Adı:");

        jLabel7.setText("Ziyaret Sebebi:");

        cbVisitD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Misafirlik", "Kargo Tesimat", "TV/İnternet Kurulum", "Sevkiyat", "Banka", "Ders/Eğitim" }));
        cbVisitD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbVisitDİtemStateChanged(evt);
            }
        });

        pnlCar.setBackground(new java.awt.Color(204, 255, 255));
        pnlCar.setBorder(javax.swing.BorderFactory.createTitledBorder("Araç Bilgileri"));
        pnlCar.setEnabled(false);

        jLabel8.setText("Araç Plakası:");

        jLabel9.setText("Araç Detay:");

        javax.swing.GroupLayout pnlCarLayout = new javax.swing.GroupLayout(pnlCar);
        pnlCar.setLayout(pnlCarLayout);
        pnlCarLayout.setHorizontalGroup(
            pnlCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(36, 36, 36)
                .addGroup(pnlCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCarPlate)
                    .addComponent(txtCarDetail))
                .addContainerGap())
        );
        pnlCarLayout.setVerticalGroup(
            pnlCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCarPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCarDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        chkCar.setText("Araç Var");
        chkCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCarActionPerformed(evt);
            }
        });

        jLabel10.setText("Ziyaret Edilen Kişi:");

        cbSelectHabitant.setMaximumRowCount(20);
        cbSelectHabitant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Ziyaret edilen Seç-" }));
        cbSelectHabitant.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSelectHabitantİtemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCampanyName)
                            .addComponent(cbVisitD, 0, 185, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chkCar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cbSelectHabitant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCampanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbVisitD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbSelectHabitant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnAddVisit.setText("Kayıt Ekle");
        btnAddVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVisitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAddVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnAddVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Visitor v;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        v = new Visitor();
        v = null;
        try {
            v = Visitors.getVisitorByTRIDNo(Long.parseLong(txtTRID.getText()));
            if (v!=null) {
                txtName.setText(v.getName());
                txtSurName.setText(v.getSurname());
                txtBirthDate.setText(String.valueOf(v.getBirthYear()));
                cbisTRS.setSelectedIndex(DBSetting.getBoolAsInt(v.getIsTRS()));
                txtBirthDate.setEnabled(false);
                txtName.setEnabled(false);
                txtName.setEnabled(false);
                txtSurName.setEnabled(false);
                cbisTRS.setEnabled(false);
                
            } else {
                JOptionPane.showMessageDialog(null, "Bu TCKNo/Telefon numarası için kayıt bulunamadı!\nYeni kişi kaydı gerekli...","SecurityX",JOptionPane.INFORMATION_MESSAGE);
                txtBirthDate.setEnabled(true);
                txtName.setEnabled(true);
                txtName.setEnabled(true);
                txtSurName.setEnabled(true);
                cbisTRS.setEnabled(true);
                jCheckBox1.setEnabled(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formİnternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formİnternalFrameOpened
        // TODO add your handling code here:
        try {
            Connection con = DBSetting.openTocan();
            PreparedStatement ps = con.prepareStatement("select CAST(HabitantID as varchar(4))+'. '+ ApartmentID+'. '+Name+' '+Surname as name from Habitants where isLeft=0 order by ApartmentID");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                cbSelectHabitant.addItem(rs.getString(1));
                
            }
        } catch (SQLException e) {
            JOptionPane.showConfirmDialog(null, "Bilgiler çekilirken bir hata oluştu!\n"+e.getMessage(),"SecurityX",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formİnternalFrameOpened

    private void chkCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCarActionPerformed
        // TODO add your handling code here:
        if(chkCar.isSelected())
            pnlCar.setEnabled(true);
        else
            pnlCar.setEnabled(false);
    }//GEN-LAST:event_chkCarActionPerformed

    private void btnAddVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVisitActionPerformed
        // TODO add your handling code here:
        Visitor va = new Visitor();
        if(txtName.isEnabled())
        {
            
            va.setName(txtName.getText());
            va.setSurname(txtSurName.getText());
            va.setTRIDNo(Long.parseLong(txtTRID.getText()));
            va.setPersonalID(frmLogin.activeUser.getPersonalID());
            va.setIsTRS(cbisTRS.getSelectedIndex()==1);
            va.setBirthYear(Integer.parseInt(txtBirthDate.getText()));
            va.setIsTRS(jCheckBox1.isSelected());
            va.setIsTRIDVerified(jCheckBox1.isSelected()==true);
            
            if(!Visitors.addToVisitors(va))
            {
                return;
            }
            v = new Visitor();
            v.setTRIDNo(va.getTRIDNo());
            v = Visitors.getVisitorByTRIDNo(v.getTRIDNo());
        }
        if (chkCar.isSelected()) {
        
             VCar CV = new VCar();
             CV.setPersonalID(frmLogin.activeUser.getPersonalID());
             CV.setVisitorID(v.getVisitorID());
             CV.setPlate(txtCarPlate.getText());
             CV.setDetail(txtCarDetail.getText());
             if(!VCars.addToVCars(CV))
             return;
        
        }
        String itmFull = String.valueOf(cbSelectHabitant.getSelectedItem());
        String[] itemsl = itmFull.split(". ");
        String deger = itemsl[0].trim();
        int vID = Integer.parseInt(deger);
        Visit vst = new Visit();
        vst.setVisitorID(v.getVisitorID());
        vst.setCompany(txtCampanyName.getText());
        vst.setHabitantID(vID);
        vst.setPersonalID(frmLogin.activeUser.getPersonalID());
        vst.setDetail(cbVisitD.getSelectedItem().toString());
        Log l = new Log();
        l.setOperation("NEWVS");
        l.setDetail("New Visit");
        l.setPersonalID(frmLogin.activeUser.getPersonalID());
        if(Visits.newVisit(vst)&&Logs.addToLog(l))
        {
            JOptionPane.showMessageDialog(null, "Kişi kaydı başarııyla eklendi!","SecurityX",JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Bir hata oluştu!","SecurityX",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddVisitActionPerformed

    private void cbVisitDİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbVisitDİtemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbVisitDİtemStateChanged

    private void cbSelectHabitantİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSelectHabitantİtemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbSelectHabitantİtemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVisit;
    private javax.swing.JComboBox<String> cbSelectHabitant;
    private javax.swing.JComboBox<String> cbVisitD;
    private javax.swing.JComboBox<String> cbisTRS;
    private javax.swing.JCheckBox chkCar;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlCar;
    private javax.swing.JTextField txtBirthDate;
    private javax.swing.JTextField txtCampanyName;
    private javax.swing.JTextField txtCarDetail;
    private javax.swing.JTextField txtCarPlate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurName;
    private javax.swing.JTextField txtTRID;
    // End of variables declaration//GEN-END:variables
}
