/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import Entities.Log;
import Entities.Personal;
import Facade.Logs;
import Facade.Personals;
import Settings.DBSetting;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author anil.senel
 */
public class ifrmMyProfile extends javax.swing.JInternalFrame {

    /**
     * Creates new form jfrmMyProfile
     */
    public ifrmMyProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBasicInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblPersonalID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTRIDNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbBDD = new javax.swing.JComboBox<>();
        cbBDm = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbisTRS = new javax.swing.JComboBox<>();
        txtDBYaer = new javax.swing.JTextField();
        pnlPass = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pOldPas = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        ppNewPass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        ppNewPassR = new javax.swing.JPasswordField();
        btnChangePass = new javax.swing.JButton();
        pnlContanct = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEMail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblSavaDate = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        lblTotalLogNumber = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 255));
        setClosable(true);
        setTitle("Hesabım");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formİnternalFrameOpened(evt);
            }
        });

        pnlBasicInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Temel Bilgiler"));
        pnlBasicInfo.setForeground(new java.awt.Color(51, 51, 55));
        pnlBasicInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setText("Adı:");

        txtName.setBackground(new java.awt.Color(0, 204, 255));
        txtName.setForeground(new java.awt.Color(51, 51, 55));

        jLabel2.setText("Soyadı:");

        txtSurname.setBackground(new java.awt.Color(0, 204, 255));
        txtSurname.setForeground(new java.awt.Color(51, 51, 55));

        jLabel3.setText("PersonelID:");

        lblPersonalID.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblPersonalID.setText("0000");

        jLabel5.setText("TC/YU No:");

        txtTRIDNo.setBackground(new java.awt.Color(0, 204, 255));
        txtTRIDNo.setForeground(new java.awt.Color(51, 51, 55));

        jLabel6.setText("Doğum Tarihi:");

        cbBDD.setBackground(new java.awt.Color(0, 204, 255));
        cbBDD.setForeground(new java.awt.Color(51, 51, 55));
        cbBDD.setMaximumRowCount(20);
        cbBDD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-gün-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbBDm.setBackground(new java.awt.Color(0, 204, 255));
        cbBDm.setForeground(new java.awt.Color(51, 51, 55));
        cbBDm.setMaximumRowCount(13);
        cbBDm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-ay-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel7.setText("Uyruk:");

        cbisTRS.setBackground(new java.awt.Color(0, 204, 255));
        cbisTRS.setForeground(new java.awt.Color(51, 51, 55));
        cbisTRS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yabancı", "Türkiye Cumhuriyeti" }));

        txtDBYaer.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout pnlBasicInfoLayout = new javax.swing.GroupLayout(pnlBasicInfo);
        pnlBasicInfo.setLayout(pnlBasicInfoLayout);
        pnlBasicInfoLayout.setHorizontalGroup(
            pnlBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBasicInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBasicInfoLayout.createSequentialGroup()
                        .addGroup(pnlBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSurname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlBasicInfoLayout.createSequentialGroup()
                                .addComponent(lblPersonalID)
                                .addGap(0, 156, Short.MAX_VALUE))
                            .addComponent(txtTRIDNo)
                            .addComponent(txtName)))
                    .addGroup(pnlBasicInfoLayout.createSequentialGroup()
                        .addGroup(pnlBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbisTRS, 0, 181, Short.MAX_VALUE)
                            .addGroup(pnlBasicInfoLayout.createSequentialGroup()
                                .addComponent(cbBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbBDm, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDBYaer)))))
                .addContainerGap())
        );
        pnlBasicInfoLayout.setVerticalGroup(
            pnlBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBasicInfoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlBasicInfoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlBasicInfoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSurname)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblPersonalID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtTRIDNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDBYaer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(cbBDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbBDm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbisTRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlPass.setBorder(javax.swing.BorderFactory.createTitledBorder("Portal Şifre Değiştirme"));
        pnlPass.setForeground(new java.awt.Color(51, 51, 55));

        jLabel8.setText("Mevcud Şifre:");

        jLabel9.setText("Yeni Şifre:");

        jLabel10.setText("Şifre Tekrar:");

        btnChangePass.setText("Şifreyi Değiştir");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPassLayout = new javax.swing.GroupLayout(pnlPass);
        pnlPass.setLayout(pnlPassLayout);
        pnlPassLayout.setHorizontalGroup(
            pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPassLayout.createSequentialGroup()
                        .addGroup(pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pOldPas)
                            .addComponent(ppNewPass)))
                    .addGroup(pnlPassLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ppNewPassR))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPassLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlPassLayout.setVerticalGroup(
            pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pOldPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ppNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ppNewPassR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChangePass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlContanct.setBorder(javax.swing.BorderFactory.createTitledBorder("İletişim Bilgileri"));

        jLabel11.setText("Telefon Numarası:");

        txtPhoneNumber.setBackground(new java.awt.Color(0, 255, 255));

        jLabel12.setText("E Posta Adresi:");

        txtEMail.setBackground(new java.awt.Color(0, 255, 255));

        jLabel13.setText("Adres:");

        txtAddress.setBackground(new java.awt.Color(0, 255, 255));
        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        txtAddress.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtAddress);

        javax.swing.GroupLayout pnlContanctLayout = new javax.swing.GroupLayout(pnlContanct);
        pnlContanct.setLayout(pnlContanctLayout);
        pnlContanctLayout.setHorizontalGroup(
            pnlContanctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContanctLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContanctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContanctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPhoneNumber)
                    .addComponent(txtEMail)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContanctLayout.setVerticalGroup(
            pnlContanctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContanctLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlContanctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContanctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGroup(pnlContanctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContanctLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContanctLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Diğer Ayrıntılar"));

        jLabel14.setText("Sisteme Kyt Tarihi:");

        lblSavaDate.setText("0000-00-00-00-00-000");

        jLabel16.setText("Yetki:");

        lblStatus.setText("jLabel17");

        jLabel18.setText("Kimlik Doğrulandı");

        jCheckBox1.setText("Kimlik Doğrulandı");

        jLabel19.setText("Toplam İşlem S:");

        lblTotalLogNumber.setText("0000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSavaDate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addGap(18, 18, 18)
                            .addComponent(lblTotalLogNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCheckBox1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblSavaDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblTotalLogNumber))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Bilgileri Güncelle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBasicInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnlContanct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlBasicInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(pnlPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlContanct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public Personal curentUser = frmLogin.activeUser;
    private void formİnternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formİnternalFrameOpened
        // TODO add your handling code here:
        txtName.setText(frmLogin.activeUser.getName());
        txtSurname.setText(frmLogin.activeUser.getSurname());
        txtTRIDNo.setText(String.valueOf(frmLogin.activeUser.getTRIDNo()));
        lblPersonalID.setText(String.valueOf(frmLogin.activeUser.getPersonalID()));
        Date trh = Date.valueOf(frmLogin.activeUser.getBirthDate().toLocalDate());
        String yil = String.valueOf(trh.getYear());
        String[] bdd = frmLogin.activeUser.getBirthDate().toString().split("-");
        cbBDD.setSelectedIndex(Integer.parseInt(bdd[2]));
        cbBDm.setSelectedIndex(Integer.parseInt(bdd[1]));
        txtDBYaer.setText(String.valueOf(trh.getYear()+1900));
        
        txtEMail.setText(frmLogin.activeUser.getEMail());
        txtPhoneNumber.setText(String.valueOf(frmLogin.activeUser.getPhoneNumber()));
        txtAddress.setText(frmLogin.activeUser.getAddress());
        lblSavaDate.setText(String.valueOf(frmLogin.activeUser.getSavaDate()));
        lblStatus.setText(String.valueOf(frmLogin.activeUser.getStatus()));
        cbisTRS.setSelectedIndex(DBSetting.getBoolAsInt(frmLogin.activeUser.getIsTRS()));
    }//GEN-LAST:event_formİnternalFrameOpened

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        // TODO add your handling code here:
        if(pOldPas.getText().trim().equals("")||ppNewPass.getText().trim().equals("")||ppNewPassR.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Boş alanları doldurun!");
            
        }
        else
        {
            if (pOldPas.getText().equals(curentUser.getPortalPass())) {
                if (ppNewPass.getText().equals(ppNewPassR.getText())) {
                    if (Personals.changePass(curentUser.getPortalPass(), ppNewPass.getText(), curentUser.getEMail())) {
                        JOptionPane.showMessageDialog(null, "Şifre başarıyla değiştirildi!\nYeniden giriş yapmalısınız.","SucurityX",JOptionPane.INFORMATION_MESSAGE);
                        System.exit(0);
                    } else {
                        JOptionPane.showMessageDialog(null, "Şifre değiştirme işlemi başarısız oldu!","SucurityX",JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Girilen Yeni şifreler eşleşmiyor!","SucurityX",JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Geçerli şifreyi yanlış girdiniz!","SucurityX",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnChangePassActionPerformed
    private Boolean checkForEmtyTextBoxs()
    {
        if (txtAddress.getText().trim().equals("")||txtDBYaer.getText().trim().equals("")||txtEMail.getText().trim().equals("")||txtName.getText().trim().equals("")||txtPhoneNumber.getText().trim().equals("")||txtSurname.getText().trim().equals("")||txtTRIDNo.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Lütfen boş alanları doldurun!","SecurityX",JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!checkForEmtyTextBoxs())
            return;
        JOptionPane.showMessageDialog(null,"Değişlikliklerin kaydetmek için şifrenizi girmeniz gerekecektir!", "SecurityX - Ek Onay",JOptionPane.WARNING_MESSAGE);
                
        JPasswordField pw = new JPasswordField(20);
        int deger = JOptionPane.showConfirmDialog(null , pw,"SecurityX - Ek Onay",JOptionPane.YES_NO_OPTION);
        if (deger != JOptionPane.OK_OPTION || deger != JOptionPane.YES_OPTION) {
            return;
        }
        if (pw.getText().equals(curentUser.getPortalPass())) {
           Personal p = curentUser;
           p.setName(txtName.getText());
           p.setSurname(txtSurname.getText());
           p.setIsTRS(cbisTRS.getSelectedIndex()==1);
           p.setBirthDate(Date.valueOf(txtDBYaer.getText()+"-"+cbBDm.getSelectedItem().toString()+"-"+cbBDD.getSelectedItem().toString()));
           p.setEMail(txtEMail.getText());
           p.setPhoneNumber(Long.parseLong(txtPhoneNumber.getText()));
           p.setAddress(txtAddress.getText());
           p.setTRIDNo(Long.parseLong(txtTRIDNo.getText()));
           Log l = new Log();
           l.setOperation("UPDP");
           l.setDetail("Personel profil guncelleme!");
           l.setPersonalID(p.getPersonalID());
            if (Personals.updatePersonal(p)) {
                Logs.addToLog(l);
                JOptionPane.showMessageDialog(null,"Sn. "+p.getSurname() + "\nBilgileriniz başarılya günllenendi!","SecurityX",JOptionPane.INFORMATION_MESSAGE);
                frmLogin.activeUser=p;
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Bilgi güncelleme hatası!","SecurityX",JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Yanlıoş şifre girişi!","SecurityX",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JComboBox<String> cbBDD;
    private javax.swing.JComboBox<String> cbBDm;
    private javax.swing.JComboBox<String> cbisTRS;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPersonalID;
    private javax.swing.JLabel lblSavaDate;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTotalLogNumber;
    private javax.swing.JPasswordField pOldPas;
    private javax.swing.JPanel pnlBasicInfo;
    private javax.swing.JPanel pnlContanct;
    private javax.swing.JPanel pnlPass;
    private javax.swing.JPasswordField ppNewPass;
    private javax.swing.JPasswordField ppNewPassR;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtDBYaer;
    private javax.swing.JTextField txtEMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtTRIDNo;
    // End of variables declaration//GEN-END:variables
}
