/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import Entities.Habitant;
import Entities.Mail;
import Entities.VCar;
import Entities.Visit;
import Entities.Visitor;
import Facade.Habitants;
import Facade.Mails;
import Facade.Visitors;
import Facade.Visits;
import Settings.DBSetting;
import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author anild
 */
public class ifrmVisits extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmVisits
     */
    public ifrmVisits() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisits = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        cbStartDate = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbEndDate = new javax.swing.JComboBox<>();
        btnDateFilter = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbPersonalSelect = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbApartment = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cbSelectHabitant = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        cbVDetail = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        txtScanForName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtVName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtVSurname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtVTRIDNo = new javax.swing.JTextField();
        txtVisTRS = new javax.swing.JCheckBox();
        txtVisTRIDVerified = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        txtVisitorID = new javax.swing.JTextField();
        txtVBirthYear = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtVSaveDate = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtVisitID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtVisitDate = new javax.swing.JTextField();
        txtVisitTime = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtVisitDetaill = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtVisitCompany = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtHabitantID = new javax.swing.JTextField();
        txtBlock = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtHNameSurname = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        txtEMail = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Ziyaretler");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formİnternalFrameOpened(evt);
            }
        });

        tblVisits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVisits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVisitsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVisits);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tarihi Göre Fitrele"));
        jPanel3.setToolTipText("");

        jLabel2.setText("dan");

        btnDateFilter.setText("Uygula");
        btnDateFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateFilterActionPerformed(evt);
            }
        });

        jButton1.setText("Sıfırla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPrint.setText("Yazdır");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(cbEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDateFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrint)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDateFilter)
                    .addComponent(jButton1)
                    .addComponent(btnPrint))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Şuna Göre Fitrele")));

        jLabel1.setText("Personel:");

        cbPersonalSelect.setMaximumRowCount(15);
        cbPersonalSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Tüm Personeller-" }));
        cbPersonalSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPersonalSelectİtemStateChanged(evt);
            }
        });

        jLabel3.setText("Daire:");

        cbApartment.setMaximumRowCount(15);
        cbApartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Tümü-" }));
        cbApartment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbApartmentİtemStateChanged(evt);
            }
        });

        jLabel17.setText("Sakin Adı:");

        cbSelectHabitant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Tümü-" }));
        cbSelectHabitant.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSelectHabitantİtemStateChanged(evt);
            }
        });

        jLabel18.setText("Sebep:");

        cbVDetail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Tümü-", "Misafirlik", "Kargo Tesimat", "TV/İnternet Kurulum", "Sevkiyat", "Banka", "Ders/Eğitim" }));
        cbVDetail.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbVDetailItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbPersonalSelect, 0, 125, Short.MAX_VALUE)
                    .addComponent(cbSelectHabitant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbApartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbVDetail, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbPersonalSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbApartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbSelectHabitant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(cbVDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Arama Yap"));

        jButton2.setText("Ara");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Tümü");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtScanForName)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtScanForName)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Ziyaretci Bilgileri"));
        jPanel6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel6KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel6KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel6KeyTyped(evt);
            }
        });

        jLabel4.setText("Adı:");

        txtVName.setBackground(new java.awt.Color(0, 255, 255));
        txtVName.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtVName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVNameKeyTyped(evt);
            }
        });

        jLabel5.setText("Soyadı:");

        txtVSurname.setBackground(new java.awt.Color(0, 255, 255));
        txtVSurname.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtVSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVSurnameKeyTyped(evt);
            }
        });

        jLabel6.setText("Telefon/TCK No:");

        txtVTRIDNo.setBackground(new java.awt.Color(0, 255, 255));
        txtVTRIDNo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        txtVisTRS.setText("TC Vatandaşı");

        txtVisTRIDVerified.setText("Kimlik Dorulandı");

        jLabel7.setText("ZiyaretciID-D. Yılı:");

        txtVisitorID.setBackground(new java.awt.Color(51, 255, 255));
        txtVisitorID.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtVisitorID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVisitorIDKeyTyped(evt);
            }
        });

        txtVBirthYear.setBackground(new java.awt.Color(51, 255, 255));
        txtVBirthYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVBirthYearKeyTyped(evt);
            }
        });

        jLabel8.setText("Sisteme Kayıt Tarihi:");

        txtVSaveDate.setBackground(new java.awt.Color(51, 255, 255));
        txtVSaveDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVSaveDateKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtVName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVSurname)
                            .addComponent(txtVTRIDNo)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtVisTRS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtVisTRIDVerified)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE))
                            .addComponent(txtVSaveDate)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(txtVisitorID, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtVName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtVSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtVTRIDNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVisTRIDVerified)
                    .addComponent(txtVisTRS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtVisitorID)
                    .addComponent(txtVBirthYear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtVSaveDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Ziyaret Bilgileri"));

        jLabel9.setText("Ziyzret ID:");

        txtVisitID.setBackground(new java.awt.Color(0, 255, 255));
        txtVisitID.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtVisitID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVisitIDKeyTyped(evt);
            }
        });

        jLabel10.setText("Ziyare Tarih ve Saati:");

        txtVisitDate.setBackground(new java.awt.Color(0, 255, 255));
        txtVisitDate.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtVisitDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVisitDateKeyTyped(evt);
            }
        });

        txtVisitTime.setBackground(new java.awt.Color(0, 255, 255));
        txtVisitTime.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtVisitTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVisitTimeKeyTyped(evt);
            }
        });

        jLabel11.setText("Ziyaret Sebebi:");

        txtVisitDetaill.setBackground(new java.awt.Color(0, 255, 255));
        txtVisitDetaill.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtVisitDetaill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVisitDetaillKeyTyped(evt);
            }
        });

        jLabel12.setText("Şirket:");

        txtVisitCompany.setBackground(new java.awt.Color(0, 255, 255));
        txtVisitCompany.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        txtVisitCompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVisitCompanyKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(70, 70, 70)
                        .addComponent(txtVisitID))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txtVisitDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVisitTime, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtVisitDetaill)
                            .addComponent(txtVisitCompany))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtVisitID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtVisitDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVisitTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(txtVisitDetaill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtVisitCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Ziyareteedilen Bilgileri"));

        jLabel13.setText("SakinID - Daire:");

        txtHabitantID.setBackground(new java.awt.Color(0, 255, 255));
        txtHabitantID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHabitantIDKeyTyped(evt);
            }
        });

        txtBlock.setBackground(new java.awt.Color(51, 255, 255));
        txtBlock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBlockKeyTyped(evt);
            }
        });

        jLabel14.setText("Sakin Adı - Soyadı:");

        txtHNameSurname.setBackground(new java.awt.Color(0, 255, 255));
        txtHNameSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHNameSurnameKeyTyped(evt);
            }
        });

        jLabel15.setText("Sakin Cep Telefonu:");

        jLabel16.setText("Sakin E Posta Adresi:");

        txtPhoneNumber.setBackground(new java.awt.Color(102, 255, 255));
        txtPhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneNumberKeyTyped(evt);
            }
        });

        txtEMail.setBackground(new java.awt.Color(51, 255, 255));
        txtEMail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtEMail.setText("jTextField2");
        txtEMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEMailKeyTyped(evt);
            }
        });

        jButton4.setText("Mail Gnder");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHNameSurname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(txtEMail)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(txtHabitantID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBlock))
                    .addComponent(txtPhoneNumber))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtHabitantID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtHNameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtEMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formİnternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formİnternalFrameOpened
        // TODO add your handling code here:
        this.setSize(1200, 760);
        try {
            Connection con = DBSetting.openTocan();
            PreparedStatement ps = con.prepareStatement("select count(VisitID),VisitDate from HomePage group by VisitDate order by VisitDate desc");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {                
                cbEndDate.addItem(rs.getString(2));
                cbStartDate.addItem(rs.getString(2));
            }
            PreparedStatement ps2 = con.prepareStatement("select top(200) VisitID as ZiyaretID,VisitorName AS ZiyaretciAdı,VisitDate as ZiyaretTarihi,VisitTime as ZiyaretSebebi from HomePage "+
                    "order by VisitID desc");
            ResultSet rs2 = ps2.executeQuery();
            tblVisits.setModel(DbUtils.resultSetToTableModel(rs2));
            
            PreparedStatement psPersonals = con.prepareStatement("select Name+' '+Surname from Personals order by Name");
            ResultSet rsPersonal = psPersonals.executeQuery();
            while (rsPersonal.next()) {                
                cbPersonalSelect.addItem(rsPersonal.getString(1));
            }
            PreparedStatement psApartments = con.prepareStatement("select ApartmentID,COUNT(VisitID) from HomePage group by ApartmentID");
            ResultSet rsApartment = psApartments.executeQuery();
            while (rsApartment.next()) {                
                cbApartment.addItem(rsApartment.getString(1));
            }
            PreparedStatement psHabitant = con.prepareStatement("select Name+' '+Surname from Habitants order by Name");
            ResultSet rscbHabitant = psHabitant.executeQuery();
            while (rscbHabitant.next()) {                
                cbSelectHabitant.addItem(rscbHabitant.getString(1));
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Veri tabanına bağladırken bir hata oluştu!\n"+e.getMessage(),"SecurityX",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formİnternalFrameOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         try {
            Connection con = DBSetting.openTocan();
           
            PreparedStatement ps2 = con.prepareStatement("select VisitID as ZiyaretID,VisitorName ZiyaretciAdı,VisitDate as ZiyaretTarihi,VisitTime as ZiyaretSaati from HomePage order by VisitID desc");
            ResultSet rs2 = ps2.executeQuery();
            tblVisits.setModel(DbUtils.resultSetToTableModel(rs2));
        } catch (SQLException e) {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDateFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateFilterActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DBSetting.openTocan();
           
            PreparedStatement ps2 = con.prepareStatement("select VisitID as ZiyaretID,VisitorName ZiyaretciAdı,VisitDate as ZiyaretTarihi,VisitTime as ZiyaretSaati from HomePage where VisitDate between ? and ?");
            ps2.setString(1, cbStartDate.getSelectedItem().toString());
            ps2.setString(2, cbEndDate.getSelectedItem().toString());
            ResultSet rs2 = ps2.executeQuery();
            tblVisits.setModel(DbUtils.resultSetToTableModel(rs2));
            
            
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btnDateFilterActionPerformed

    private void cbPersonalSelectİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPersonalSelectİtemStateChanged
        // TODO add your handling code here:
        try {
            Connection con = DBSetting.openTocan();
            if(cbPersonalSelect.getSelectedIndex()!=0)
            {                 
                 PreparedStatement ps = con.prepareStatement("select VisitID as ZiyaretID,VisitorName ZiyaretciAdı,VisitDate as ZiyaretTarihi,VisitTime as ZiyaretSaati from HomePage "
                         + "where PersonalName=?");
                 ps.setString(1, cbPersonalSelect.getSelectedItem().toString());
                 ResultSet rs2 = ps.executeQuery();
                 tblVisits.setModel(DbUtils.resultSetToTableModel(rs2));
            }
            else
            {
                PreparedStatement ps2 = con.prepareStatement("select VisitID,VisitorName,VisitDate,VisitTime from HomePage");
                ResultSet rs2 = ps2.executeQuery();
                tblVisits.setModel(DbUtils.resultSetToTableModel(rs2));
            }
           
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_cbPersonalSelectİtemStateChanged
    private void showDeta(int id)
    {
        try {
            Visit gVisit = Visits.getVisitByID(id);
            //JOptionPane.showConfirmDialog(null, "visit");
            Visitor gVisitor = Visitors.getVisitorByVisitorID(gVisit.getVisitorID());
           // JOptionPane.showConfirmDialog(null, "visitor");
            Habitant gHabitant = Habitants.getHabitantByID(gVisit.getHabitantID());
           // JOptionPane.showConfirmDialog(null, "0");
            //Ziyaret
            txtVisitID.setText(String.valueOf(gVisit.getVisitID()));
            txtVisitDetaill.setText(gVisit.getDetail());
            txtVisitCompany.setText(gVisit.getCompany());
            txtVisitDate.setText(String.valueOf(tblVisits.getValueAt(tblVisits.getSelectedRow(), 2)));
            txtVisitTime.setText(String.valueOf(tblVisits.getValueAt(tblVisits.getSelectedRow(), 3)));
            //Ziyaretci
            txtVisitorID.setText(String.valueOf(gVisitor.getVisitorID()));
            txtVBirthYear.setText(String.valueOf(gVisitor.getBirthYear()));
            txtVName.setText(gVisitor.getName());
            txtVSurname.setText(gVisitor.getSurname());
            txtVTRIDNo.setText(String.valueOf(gVisitor.getTRIDNo()));
            txtVSaveDate.setText(String.valueOf(gVisitor.getSaveDate()));
            txtVisTRS.setSelected(gVisitor.getIsTRS());
            txtVisTRIDVerified.setSelected(gVisitor.getIsTRIDVerified());
            //Sakin
            txtHabitantID.setText(String.valueOf(gVisit.getHabitantID()));
            txtBlock.setText(gHabitant.getApartmentID());
            txtHNameSurname.setText(gHabitant.getName()+" "+gHabitant.getSurname());
            txtEMail.setText(gHabitant.getEMail());
            txtPhoneNumber.setText(String.valueOf(gHabitant.getPhoneNumber()));
                    
            
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(null, "Bir hata oluştu!\n"+e.getMessage()+"\n"+e.getLocalizedMessage(),"SecurityX",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void tblVisitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVisitsMouseClicked
        // TODO add your handling code here:
        try {
            String value = String.valueOf(tblVisits.getValueAt(tblVisits.getSelectedRow(), 0));
            //JOptionPane.showMessageDialog(null, value);
            int id = Integer.parseInt(value);
            showDeta(id);
        } catch (NumberFormatException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Veri çekilirken hata oluştu!\n"+e.getMessage(),"SecurityX",JOptionPane.ERROR_MESSAGE);
        } catch(RuntimeException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tblVisitsMouseClicked

    private void jPanel6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel6KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel6KeyPressed

    private void jPanel6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel6KeyReleased
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jPanel6KeyReleased

    private void jPanel6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel6KeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_jPanel6KeyTyped

    private void txtVNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVNameKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_txtVNameKeyTyped

    private void cbApartmentİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbApartmentİtemStateChanged
        // TODO add your handling code here:
        try {
            if (cbApartment.getSelectedIndex()==0) {
                Connection con = DBSetting.openTocan();      
                PreparedStatement ps2 = con.prepareStatement("select top(50) VisitID,VisitorName,VisitDate,VisitTime from HomePage"
                        + " order by VisitID desc");
                ResultSet rs2 = ps2.executeQuery();
                tblVisits.setModel(DbUtils.resultSetToTableModel(rs2));
                
            } else {
                Connection con = DBSetting.openTocan();
           
                PreparedStatement ps2 = con.prepareStatement("select VisitID,VisitorName,VisitDate,VisitTime from HomePage"
                        + " where ApartmentID='"+cbApartment.getSelectedItem().toString().trim()+"' order by VisitID desc");
                ResultSet rs2 = ps2.executeQuery();
                tblVisits.setModel(DbUtils.resultSetToTableModel(rs2));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Listeleme hatası!\n"+e.getMessage(),"SecurityX",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cbApartmentİtemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
             Connection con = DBSetting.openTocan();      
             PreparedStatement ps2 = con.prepareStatement("select top(50) VisitID as ZiyaretID,VisitorName as ZiyaretciAdı,VisitDate as ZiyaretTarihi,VisitTime as ZiyaretSaati from HomePage"
                        + " order by VisitID desc");
             ResultSet rs2 = ps2.executeQuery();
            tblVisits.setModel(DbUtils.resultSetToTableModel(rs2));
                
           
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Listeleme hatası!\n"+e.getMessage(),"SecurityX",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (txtScanForName.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Aranaçak isim alanı boş bırakılamaz!","SecurityX",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try {
          
                Connection con = DBSetting.openTocan();
           
                PreparedStatement ps2 = con.prepareStatement("select VisitID AS ZiyaretID,VisitorName as ZiyaretciAdı,VisitDate as ZiyaretTarihi,VisitTime as ZiyaretSaati from HomePage"
                        + " where VisitorName like '%"+txtScanForName.getText().toUpperCase()+"%' or VisitedName like '%"+txtScanForName.getText().toUpperCase()+"%' order by VisitID desc");
               // ps2.setString(1, txtScanForName.getText().toUpperCase());
                ResultSet rs2 = ps2.executeQuery();
                tblVisits.setModel(DbUtils.resultSetToTableModel(rs2));
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Listeleme hatası!\n"+e.getMessage(),"SecurityX",JOptionPane.ERROR_MESSAGE);
        }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtVSurnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVSurnameKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_txtVSurnameKeyTyped

    private void txtVisitorIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVisitorIDKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_txtVisitorIDKeyTyped

    private void txtVBirthYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVBirthYearKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_txtVBirthYearKeyTyped

    private void txtVSaveDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVSaveDateKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_txtVSaveDateKeyTyped

    private void txtVisitIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVisitIDKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_txtVisitIDKeyTyped

    private void txtVisitDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVisitDateKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_txtVisitDateKeyTyped

    private void txtVisitDetaillKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVisitDetaillKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_txtVisitDetaillKeyTyped

    private void txtEMailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEMailKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_txtEMailKeyTyped

    private void txtPhoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_txtPhoneNumberKeyTyped

    private void txtHNameSurnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHNameSurnameKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_txtHNameSurnameKeyTyped

    private void txtHabitantIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHabitantIDKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_txtHabitantIDKeyTyped

    private void txtBlockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBlockKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_txtBlockKeyTyped

    private void txtVisitCompanyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVisitCompanyKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_txtVisitCompanyKeyTyped

    private void txtVisitTimeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVisitTimeKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_txtVisitTimeKeyTyped

    private void cbSelectHabitantİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSelectHabitantİtemStateChanged
        // TODO add your handling code here:
        try {
            Connection con = DBSetting.openTocan();
            if(cbSelectHabitant.getSelectedIndex()!=0)
            {                 
                 PreparedStatement ps = con.prepareStatement("select VisitID,VisitorName,VisitDate,VisitTime from HomePage "
                         + "where VisitedName=?");
                 ps.setString(1, cbSelectHabitant.getSelectedItem().toString().toUpperCase());
                 ResultSet rs2 = ps.executeQuery();
                 tblVisits.setModel(DbUtils.resultSetToTableModel(rs2));
                 if (tblVisits.getModel().getRowCount()==0) {
                    JOptionPane.showMessageDialog(null, "Eşleşen kayıt bulanamadı!","SecurityX",JOptionPane.WARNING_MESSAGE);
                }
            }
            else
            {
                PreparedStatement ps2 = con.prepareStatement("select VisitID,VisitorName,VisitDate,VisitTime from HomePage");
                ResultSet rs2 = ps2.executeQuery();
                tblVisits.setModel(DbUtils.resultSetToTableModel(rs2));
                
            }
           
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Verileri çekerken bir hata oluştu!\n"+e.getMessage(),"SecurityX",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cbSelectHabitantİtemStateChanged

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try {
            MessageFormat hdr = new MessageFormat("SucurityX Ziyaret Dökümü");
            MessageFormat ftr = new MessageFormat(frmLogin.activeUser.getName()+" "+frmLogin.activeUser.getSurname()+" tarafından Çıkartıldı!");
            tblVisits.print(JTable.PrintMode.NORMAL,hdr,ftr);
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, "Yazdırma sırasında bir hata oluştu!\n-"+e.getMessage());
        
    }//GEN-LAST:event_btnPrintActionPerformed

        
    private void cbVDetailItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbVDetailItemStateChanged
        int a = evt.getID();
        try {
            Connection con = DBSetting.openTocan();
            if(cbVDetail.getSelectedIndex()!=0)
            {                 
                 PreparedStatement ps = con.prepareStatement("select hg.VisitID as ZiyaretID,VisitorName as ZiyaretciAdı,hg.VisitDate as ZiyaretTarihi,VisitTime as ZiyaretSaati from HomePage as hg " +
"inner join Visits on hg.VisitID=Visits.VisitID where Visits.Detail like '%"+cbVDetail.getSelectedItem().toString()+"%'");
                 ResultSet rs2 = ps.executeQuery();
                 tblVisits.setModel(DbUtils.resultSetToTableModel(rs2));
                 if (tblVisits.getModel().getRowCount()==0) {
                    JOptionPane.showMessageDialog(null, "Eşleşen kayıt bulanamadı!","SecurityX",JOptionPane.WARNING_MESSAGE);
                }
            }
            else
            {
                PreparedStatement ps2 = con.prepareStatement("select VisitID as ZiyaretID,VisitorName as ZiyaretciAdı,VisitDate as ZiyaretTarihi,VisitTime as ZiyaretSaati from HomePage");
                ResultSet rs2 = ps2.executeQuery();
                tblVisits.setModel(DbUtils.resultSetToTableModel(rs2));
                
            }
           
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Verileri çekerken bir hata oluştu!\n"+e.getMessage(),"SecurityX",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cbVDetailItemStateChanged

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        
         Mail m = new Mail();
        m.setSing(frmLogin.activeUser.getSurname()+" tarafından gönderildi...");
        String[] ary = {txtEMail.getText().toLowerCase()};
        JTextArea txtBady = new JTextArea(8,8);
        m.setSubject(JOptionPane.showInputDialog(null,"Lütfen E Postanın konusunu girin...","SecurityX - E Posata - Konu",JOptionPane.INFORMATION_MESSAGE));
        int a = JOptionPane.showConfirmDialog(null, txtBady,"SecurityX - E Posata İçerik...",JOptionPane.YES_NO_OPTION);
        if (a==JOptionPane.YES_OPTION) {
            m.setBody(txtBady.getText());
        }
        else
        {
            return;
        }
        m.setEMail(txtEMail.getText());
        int b = JOptionPane.showConfirmDialog(null, "Alıcı:\t"+txtHNameSurname.getText()+"\nKonu:\t"+
                m.getSubject()+"İçerik:\t"+txtBady.getText()+"imza:\t"+m.getSing()+"\n-E Posata gönderilsin mi?","E Posta onay",JOptionPane.YES_NO_OPTION);
        if (a==JOptionPane.YES_OPTION) {
            if (Mails.sendAMail(m, ary, ary.length)) {
                JOptionPane.showMessageDialog(null, "E Posta başarıyla gönderildi!","SecurityX - E Posata Gönder",JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(null, "E Posta gönderirken hata oluştu!","SecurityX - E Posata Gönder",JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_jButton4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDateFilter;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox<String> cbApartment;
    private javax.swing.JComboBox<String> cbEndDate;
    private javax.swing.JComboBox<String> cbPersonalSelect;
    private javax.swing.JComboBox<String> cbSelectHabitant;
    private javax.swing.JComboBox<String> cbStartDate;
    private javax.swing.JComboBox<String> cbVDetail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVisits;
    private javax.swing.JTextField txtBlock;
    private javax.swing.JTextField txtEMail;
    private javax.swing.JTextField txtHNameSurname;
    private javax.swing.JTextField txtHabitantID;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtScanForName;
    private javax.swing.JTextField txtVBirthYear;
    private javax.swing.JTextField txtVName;
    private javax.swing.JTextField txtVSaveDate;
    private javax.swing.JTextField txtVSurname;
    private javax.swing.JTextField txtVTRIDNo;
    private javax.swing.JCheckBox txtVisTRIDVerified;
    private javax.swing.JCheckBox txtVisTRS;
    private javax.swing.JTextField txtVisitCompany;
    private javax.swing.JTextField txtVisitDate;
    private javax.swing.JTextField txtVisitDetaill;
    private javax.swing.JTextField txtVisitID;
    private javax.swing.JTextField txtVisitTime;
    private javax.swing.JTextField txtVisitorID;
    // End of variables declaration//GEN-END:variables
}
