/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import Entities.Log;
import Entities.Mail;
import Entities.Personal;
import Facade.Logs;
import Facade.Mails;
import Facade.Personals;
import Settings.*;
import java.net.ConnectException;
import java.sql.*;
import java.util.ResourceBundle;
import javafx.scene.control.ComboBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author anil.senel
 */
public class ifrmLisitPersonals extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmLisitPersonals
     */
    public ifrmLisitPersonals() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbisTRS = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtTRIDNo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbDay = new javax.swing.JComboBox<>();
        cbMoth = new javax.swing.JComboBox<>();
        txtYear = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        chisTRIDVerified = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        txtEMail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        txtSaveDate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnSaveUpdate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbSelectPersonals = new javax.swing.JComboBox<>();
        btnApply = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tbtnStartEditing = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Personelleri Yönet");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Personel Bilgileri"));

        jLabel2.setText("PesonelID:");

        lblID.setText("0000");

        jLabel4.setText("İsim:");

        jLabel5.setText("Soyisim:");

        jLabel6.setText("Uyruk:");

        cbisTRS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yabancı", "TC. Vatandaşı" }));

        jLabel7.setText("T.C Kimlik No:");

        jLabel8.setText("Doğum Tarihi:");

        cbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-gün-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbMoth.setMaximumRowCount(13);
        cbMoth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-ay-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel9.setText("Kimlik Doğrulanma Durumu:");

        chisTRIDVerified.setText("Doğrulanmadı");

        jLabel10.setText("E Posta Adresi:");

        jLabel11.setText("Cep Telefonu:");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jLabel12.setText("Adres:");

        txtSaveDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaveDateKeyTyped(evt);
            }
        });

        jLabel13.setText("Sisteme Kayıt Tarihi:");

        btnSaveUpdate.setText("Bilgileri Güncelle");
        btnSaveUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUpdateActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Personellere Genel Bakış"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chisTRIDVerified)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSaveDate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEMail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTRIDNo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbisTRS, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblID)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtSurname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMoth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtYear))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSaveUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbisTRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTRIDNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMoth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(chisTRIDVerified))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtEMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSaveDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaveUpdate))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setText("Bir Perfonel Seç");

        cbSelectPersonals.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSelectPersonalsİtemStateChanged(evt);
            }
        });

        btnApply.setText("Yetki Değiştir");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        jButton1.setText("Parolayı Sıfırla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbtnStartEditing.setText("Düzenlemeye Başla");
        tbtnStartEditing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnStartEditingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbSelectPersonals, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbtnStartEditing)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbSelectPersonals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApply)
                    .addComponent(jButton1)
                    .addComponent(tbtnStartEditing))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        tbtnStartEditingActionPerformed(null);
        try {
            Connection con = DBSetting.openTocan();
            PreparedStatement ps = con.prepareStatement("select cast(PersonalID as varchar(3)) +' '+Name+' '+Surname from Personals");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {                
                cbSelectPersonals.addItem(rs.getString(1));
            }
            PreparedStatement psTable = con.prepareStatement("select Name as Adı,Surname as Soyadı,Status as Durum from Personals");
            jTable1.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(psTable.executeQuery()));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Veriler çekilirken hata oluştu!\n","SecurityX",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formInternalFrameOpened
    Personal curentPersonal;
    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        // TODO add your handling code here:
        JComboBox cb = new JComboBox();
        cb.addItem("Standart");
        cb.addItem("Yönetici");
        cb.addItem("Askıda");
        
        switch(curentPersonal.getStatus())
        {
            case -1:
                cb.setSelectedIndex(2);
                break;
            case 0:
                cb.setSelectedIndex(0);
                break;
            default:
                cb.setSelectedIndex(1);
                break;
        }
        int a = JOptionPane.showConfirmDialog(null, cb,"Yetki Seçin",JOptionPane.OK_CANCEL_OPTION);
        if (a==JOptionPane.OK_OPTION) {
            JPasswordField pw = new JPasswordField(20);
            JOptionPane.showMessageDialog(null, "İşlemi onaylamak için Prtal Şifrenizi girmeniz istecenektir...","SecurityX - Ek Onay",JOptionPane.INFORMATION_MESSAGE);
            int aap = JOptionPane.showConfirmDialog(null, pw,"SecurityX - Portal Şifrenizi girin",JOptionPane.OK_CANCEL_OPTION);
            if (aap==JOptionPane.OK_OPTION) {
                if (pw.getText().equals(frmLogin.activeUser.getPortalPass())) {
                    Personal p = curentPersonal;
                    switch(cb.getSelectedIndex())
                    {
                        case 0:
                            p.setStatus(0);
                            JOptionPane.showMessageDialog(null, "Standart kullanıcı:Temel İşlemlerin tamamamını gerçekleştirebilir ancak yönetim menüsüne ulaşamaz!","SecurityX - Bilgi",JOptionPane.WARNING_MESSAGE);
                            break;
                        case 1:
                            p.setStatus(1);
                            JOptionPane.showMessageDialog(null, "Yönetici:\nTüm işlemleri gerçekleştirebilir!","SecurityX - Bilgi",JOptionPane.WARNING_MESSAGE);
                            break;
                        case 2:
                            p.setStatus(-1);
                            JOptionPane.showMessageDialog(null, "Askıya alınan hesap sisteme erişemez!","SecurityX - Bilgi",JOptionPane.WARNING_MESSAGE);
                            break;
                    }
                    Log l = new Log();
                    l.setDetail("UPDP");
                    l.setPersonalID(frmLogin.activeUser.getPersonalID());
                    l.setDetail("Personel durumu degistirildi...PID:"+lblID.getText());
                    if (Personals.changePersonalStatus(p)) {
                        Logs.addToLog(l);
                        JOptionPane.showMessageDialog(null, "Personel yetkisi güncellendi!","SecurityX",JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Güncelleme sırasında bir hata oluştu","SecurityX",JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Girilen şifre yanlış!","SecurityX - Ek Onay Hatası",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
    }//GEN-LAST:event_btnApplyActionPerformed
    void printInfo()
    {
        lblID.setText(String.valueOf(curentPersonal.getPersonalID()));
        txtName.setText(curentPersonal.getName());
        txtSurname.setText(curentPersonal.getSurname());
        txtTRIDNo.setText(String.valueOf(curentPersonal.getTRIDNo()));
        cbisTRS.setSelectedIndex(DBSetting.getBoolAsInt(curentPersonal.getIsTRS()));
        chisTRIDVerified.setSelected(curentPersonal.getIsTRIDVerified());
        txtEMail.setText(curentPersonal.getEMail());
        txtAddress.setText(curentPersonal.getAddress());
        txtPhoneNumber.setText(String.valueOf(curentPersonal.getTRIDNo()));
        Date d = curentPersonal.getBirthDate();
        
        String[] bdd = curentPersonal.getBirthDate().toString().split("-");
        cbDay.setSelectedIndex(Integer.parseInt(bdd[2]));
        cbMoth.setSelectedIndex(Integer.parseInt(bdd[1]));
        
        txtYear.setText(String.valueOf(d.getYear()+1900));
        txtSaveDate.setText(String.valueOf(curentPersonal.getSavaDate()));
    }
    private void cbSelectPersonalsİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSelectPersonalsİtemStateChanged
        // TODO add your handling code here:
        String[] myAry = cbSelectPersonals.getSelectedItem().toString().split(" ");
        int a = Integer.parseInt(myAry[0]);
        curentPersonal = Personals.getPersonalByID(a);
        printInfo();
        
    }//GEN-LAST:event_cbSelectPersonalsİtemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JPasswordField pw = new JPasswordField(25);
        JOptionPane.showMessageDialog(null, "Parola sıfırlama işlemi için bir sonraki adımda portal şifrenizi girmediz talep edilecektir...","SecurityX - Ek onay gerekli",JOptionPane.INFORMATION_MESSAGE);
        int value = JOptionPane.showConfirmDialog(null,pw,"Onaylamak için lütfen portal şifrenizi girin...",JOptionPane.OK_CANCEL_OPTION);
        if (value==JOptionPane.OK_OPTION){
            if (pw.getText().equals(frmLogin.activeUser.getPortalPass())) {
                String  pa = OtherSettings.ganeratePass();
                Mail m = new Mail();
                m.setSubject("SecurityX - Porola Sıfırlandı");
                m.setBody("Sn. "+curentPersonal.getSurname()+"\nPortal paralanız sıfırlandı yeni şifreniz...\n"+pa);
                m.setSing(frmLogin.activeUser.getName()+" "+frmLogin.activeUser.getSurname());    
                m.setEMail(curentPersonal.getEMail());
                String ary[] = {curentPersonal.getEMail()};
                
                if(Personals.changePass(curentPersonal.getPortalPass(), pa, curentPersonal.getEMail())  && Mails.sendAMail(m, ary, ary.length))
                    JOptionPane.showMessageDialog(null, "Şifre sıfırlama işlemi başarılı!\nYeni şifre E Posta olarak Sn. "+curentPersonal.getSurname(),"SecurityX",JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(null, "Girilen şifre yanlış!","SecurityX",JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Girilen şifre yanlış!","SecurityX",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbtnStartEditingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnStartEditingActionPerformed
        // TODO add your handling code here:
        Boolean truee;
        truee = tbtnStartEditing.isSelected();
        txtAddress.setEnabled(truee);
            txtEMail.setEnabled(truee);
            txtName.setEnabled(truee);
            txtPhoneNumber.setEnabled(truee);
            txtSaveDate.setEnabled(truee);
            txtSurname.setEnabled(truee);
            txtTRIDNo.setEnabled(truee);
            txtYear.setEnabled(truee);
            cbDay.setEnabled(truee);
            cbMoth.setEnabled(truee);
            //cbSelectPersonals.setEnabled(truee);
            cbisTRS.setEnabled(truee);
            btnSaveUpdate.setEnabled(truee);
    }//GEN-LAST:event_tbtnStartEditingActionPerformed
    Boolean checkForSpaces()
    {
        return (txtAddress.getText().trim().equals("")||txtEMail.getText().trim().equals("")||txtName.getText().trim().equals("")||
                txtPhoneNumber.getText().trim().equals("")||txtSurname.getText().trim().equals("")||txtTRIDNo.getText().trim().equals("")||
                txtYear.getText().trim().equals("")||cbDay.getSelectedIndex()==0||cbMoth.getSelectedIndex()==0);
    }
    private void btnSaveUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUpdateActionPerformed
        // TODO add your handling code here:
        if (checkForSpaces()) {
            JOptionPane.showMessageDialog(null, "Boş alan bırakmayın!","SecurityX",JOptionPane.ERROR_MESSAGE);
            return;
        }
        JPasswordField pw = new JPasswordField(25);
        JOptionPane.showMessageDialog(null, "Güncelleme işleminin onayı için bir sonraki adımda portal şifrenizi girmediz talep edilecektir...","SecurityX - Ek onay gerekli",JOptionPane.INFORMATION_MESSAGE);
        int value = JOptionPane.showConfirmDialog(null,pw,"Onaylamak için lütfen portal şifr",JOptionPane.OK_CANCEL_OPTION);
        if (value==JOptionPane.OK_OPTION){
            if (pw.getText().equals(frmLogin.activeUser.getPortalPass())) 
            {
                Personal p = curentPersonal;
                p.setName(txtName.getText());
                p.setSurname(txtSurname.getText());
                p.setTRIDNo(Long.parseLong(txtTRIDNo.getText()));
                p.setBirthDate(Date.valueOf(txtYear.getText().trim()+"-"+cbMoth.getSelectedItem().toString()+"-"+cbDay.getSelectedItem().toString()));
                p.setIsTRS(cbisTRS.getSelectedIndex()==1);
                p.setIsTRIDVerified(chisTRIDVerified.isSelected());
                p.setEMail(txtEMail.getText());
                p.setPhoneNumber(Long.parseLong(txtPhoneNumber.getText()));
                p.setAddress(txtAddress.getText());
                
                Log l = new Log();
                l.setOperation("UPDP");
                l.setDetail("Update Personal ID:"+String.valueOf(curentPersonal.getPersonalID()));
                l.setPersonalID(frmLogin.activeUser.getPersonalID());
                
                if (Personals.updatePersonal(p)&&Logs.addToLog(l)) {
                    tbtnStartEditing.setSelected(false);
                    tbtnStartEditingActionPerformed(null);
                    cbSelectPersonalsİtemStateChanged(null);
                    formInternalFrameOpened(null);
                    JOptionPane.showMessageDialog(null, "Bilgi güncelleme işlemi başarıyla tamamlandı!","SecurityX",JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Güncelleme sırasında bir hata oluştu!","SecurityX",JOptionPane.ERROR_MESSAGE);
                }
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Girilen şifre yanlış olduğu için işlem gerçekleştirelemedi!","SecurityX",JOptionPane.ERROR_MESSAGE);
            }
        }
            
    }//GEN-LAST:event_btnSaveUpdateActionPerformed

    private void txtSaveDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaveDateKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_txtSaveDateKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnSaveUpdate;
    private javax.swing.JComboBox<String> cbDay;
    private javax.swing.JComboBox<String> cbMoth;
    private javax.swing.JComboBox<String> cbSelectPersonals;
    private javax.swing.JComboBox<String> cbisTRS;
    private javax.swing.JCheckBox chisTRIDVerified;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblID;
    private javax.swing.JToggleButton tbtnStartEditing;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSaveDate;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtTRIDNo;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
